trigger:
- none


stages:
 - stage: Deploy_Terraform_IaC
   displayName: "Prepare and Deploy Terraform IaC"
   jobs:
   - job: Deploy_Terraform
     pool:
       name: pkaan-selfhost-pool
       vmImage: ubuntu-latest
     steps:
     - task: TerraformInstaller@0
       displayName: "Install Terraform"
       inputs:
         terraformVersion: 'latest'
     - script: |
         terraform init
       displayName: 'Terraform init'
     - script: |
         terraform import azurerm_resource_group.rg /subscriptions/4b9c23f1-02d5-4863-9c82-9fa1098c566d/resourceGroups/pkaan_terraform_group
         terraform import azurerm_service_plan.appserviceplan /subscriptions/4b9c23f1-02d5-4863-9c82-9fa1098c566d/resourceGroups/pkaan_terraform_group/providers/Microsoft.Web/serverfarms/webapp-asp-pkaan-terraform
         terraform import azurerm_windows_web_app.webapp /subscriptions/4b9c23f1-02d5-4863-9c82-9fa1098c566d/resourceGroups/pkaan_terraform_group/providers/Microsoft.Web/sites/webapp-pkaan-terraform
         terraform plan -out=appresources.tfplan
         terraform apply appresources.tfplan
       displayName: 'Terraform Plan & Apply'